version: "3"
services:
    mongodb:
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
    coreserver:
        image: pyramidslab/cronbot-core
        depends_on:
            - mongodb
        environment:
            - MONGO_HOST=mongodb://localhost:27017
            - MONGO_DB=test            
        ports:
            - 8080:8080
        # Optional to replace application.yml file
        volumes: 
         - ./core-server:/config
    mq:
        image: rabbitmq:3-management
        ports: 
            - 5672:5672
        volumes: 
         - ./mq:/var/lib/rabbitmq/mnesia
